#ifndef CONSTANTS_H
#define CONSTANTS_H
#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 800
#define GAMEBOX_WIDTH 600
#define GAMEBOX_HEIGHT 600
#define GAMEBOX_X 100
#define GAMEBOX_Y 100


#define GRID_COLS 4
#define GRID_ROWS 4

#define CELL_WIDTH GAMEBOX_WIDTH / GRID_COLS
#define CELL_HEIGHT GAMEBOX_HEIGHT / GRID_ROWS

#define PIECE_MOVE_TIME 0.2f
#define PIECE_SPAWN_TIME 0.15f

#define STATE_TRANSITION_TIME 1.25f
#define STATE_DELAY_TIME 2.0f

#endif
